services:
  postgres:
    container_name: seekhub-postgres
    restart: always
    build:
      context: ./postgres/
      dockerfile: Dockerfile
    volumes:
      - ./postgres/data/:/var/lib/postgresql/data/
    env_file:
      - ./postgres/.env
    ports:
      - 5432:5432
  redis:
    container_name: seekhub-redis
    restart: always
    image: redis:7.4.1
    expose:
      - 6379
  backend:
    container_name: seekhub-backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
    command: fastapi dev main.py --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend/:/usr/src/app/
    env_file:
      - ./backend/.env
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - redis
  frontend:
    container_name: seekhub-frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - ./frontend/:/usr/src/app/
      - /usr/src/app/node_modules/
    ports:
      - 3000:3000
    depends_on:
      - backend
