"""Cities Model

Revision ID: 5085a2ce44e9
Revises: f0c622dcae57
Create Date: 2025-02-21 13:19:42.333560

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "5085a2ce44e9"
down_revision: Union[str, None] = "f0c622dcae57"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cities",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "name",
            sqlmodel.sql.sqltypes.AutoString(length=150),
            nullable=False,
        ),
        sa.Column(
            "name_ascii",
            sqlmodel.sql.sqltypes.AutoString(length=150),
            nullable=False,
        ),
        sa.Column(
            "location",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column(
            "country",
            sqlmodel.sql.sqltypes.AutoString(length=100),
            nullable=False,
        ),
        sa.Column(
            "country_code",
            sqlmodel.sql.sqltypes.AutoString(length=3),
            nullable=False,
        ),
        sa.Column(
            "region",
            sqlmodel.sql.sqltypes.AutoString(length=150),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_cities_location",
        "cities",
        ["location"],
        unique=False,
        postgresql_using="gist",
        if_not_exists=True,
    )
    op.create_index(
        op.f("ix_cities_country_code"),
        "cities",
        ["country_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cities_location"), "cities", ["location"], unique=False
    )
    op.create_index(op.f("ix_cities_name"), "cities", ["name"], unique=False)
    op.create_index(
        op.f("ix_cities_name_ascii"), "cities", ["name_ascii"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cities_name_ascii"), table_name="cities")
    op.drop_index(op.f("ix_cities_name"), table_name="cities")
    op.drop_index(op.f("ix_cities_location"), table_name="cities")
    op.drop_index(op.f("ix_cities_country_code"), table_name="cities")
    op.drop_index(
        "idx_cities_location", table_name="cities", postgresql_using="gist"
    )
    op.drop_table("cities")
    # ### end Alembic commands ###
