"""Profiles Model

Revision ID: a381a39485e2
Revises: 1fcc0f0ff32d
Create Date: 2025-01-18 14:16:45.428333

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "a381a39485e2"
down_revision: Union[str, None] = "1fcc0f0ff32d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profiles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "heading",
            sqlmodel.sql.sqltypes.AutoString(length=50),
            nullable=True,
        ),
        sa.Column("city_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["city_id"], ["cities.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("profiles")
    # ### end Alembic commands ###
